export const CAR_BOOKING_PURPOSES = [
  'Bring Local Staff',
  'Pick up Local Staff',
  'Pick Up K Joe (GM)',
  'Bring K Joe (GM)',
  'Bring Guest',
  'Pick up FM',
  'Pick up Foreigner',
  'Bring Foreigner',
  'Pick up Guest',
  'Meeting',
  'Release Document',
  'Submit payment',
  'Collect doc back',
  'Revise Document',
  'Send the fabric',
  'Pick  parcel',
  'Bring binding tape',
  'Pick up Accessory',
  'Pay for NSSF',
  'Withdraw',
  'Send Document TT',
  'Pick up SGS inspector',
]